// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFpvvBRnC6ItIjZUvEE-xWNN8NBUQ5RuQ',
    appId: '1:1006300423202:web:da735b7fafcee64e84967b',
    messagingSenderId: '1006300423202',
    projectId: 'warecheap-8a1cd',
    authDomain: 'warecheap-8a1cd.firebaseapp.com',
    storageBucket: 'warecheap-8a1cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUZJj2HoEKuRL7BTpYHdZ8LSPpoc89li8',
    appId: '1:1006300423202:android:65aed3b6ed7886e184967b',
    messagingSenderId: '1006300423202',
    projectId: 'warecheap-8a1cd',
    storageBucket: 'warecheap-8a1cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd9MAPAyopbT8Crdt2ck1Ib0TVfhEltUQ',
    appId: '1:1006300423202:ios:247b95b66bfaf1be84967b',
    messagingSenderId: '1006300423202',
    projectId: 'warecheap-8a1cd',
    storageBucket: 'warecheap-8a1cd.appspot.com',
    iosBundleId: 'com.example.warecheap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd9MAPAyopbT8Crdt2ck1Ib0TVfhEltUQ',
    appId: '1:1006300423202:ios:08036efdc3359a3284967b',
    messagingSenderId: '1006300423202',
    projectId: 'warecheap-8a1cd',
    storageBucket: 'warecheap-8a1cd.appspot.com',
    iosBundleId: 'com.example.warecheap.RunnerTests',
  );
}
